# Generated by Django 5.0.1 on 2024-02-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(related_name='customers', to='products.product'),
        ),
    ]
