# Generated by Django 5.0.1 on 2024-02-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_image_link_alter_image_customer_alter_image_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
