# Generated by Django 5.0.1 on 2024-02-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.AddField(
            model_name='video',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
