# Generated by Django 5.0.1 on 2024-02-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_remove_video_file_video_link'),
        ('projects', '0003_project_main_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='videos', to='projects.project'),
        ),
    ]
