# Generated by Django 5.0.1 on 2024-02-09 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('small_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('PT', 'PART'), ('SR', 'SERVICE'), ('CL', 'CLASS'), ('PR', 'PROJECT'), ('EV', 'EVENT')], max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('preamble', models.TextField()),
                ('main_picture', models.ImageField(null=True, upload_to='')),
                ('type', models.CharField(choices=[('PT', 'PART'), ('SR', 'SERVICE'), ('CL', 'CLASS'), ('PR', 'PROJECT'), ('EV', 'EVENT')], max_length=7, null=True)),
                ('carousel', models.BooleanField(default=False)),
                ('vehicle', models.CharField(choices=[('HV', 'HEAVY'), ('LT', 'LIGHT')], default='LT', max_length=10)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='entities.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.category')),
                ('entities', models.ManyToManyField(blank=True, to='entities.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('field', models.TextField()),
                ('entities', models.ManyToManyField(to='entities.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
