# Generated by Django 5.0.1 on 2024-02-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_remove_entity_category_entity_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='category',
        ),
        migrations.AddField(
            model_name='entity',
            name='categories',
            field=models.ManyToManyField(related_name='entities', to='entities.category'),
        ),
    ]
