# Generated by Django 5.0.1 on 2024-02-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
