# Generated by Django 5.0.1 on 2024-02-03 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_small_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('PRODUCT', 'PR'), ('SERVICE', 'SR'), ('CLASS', 'CL')], max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='level1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='level2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='level3',
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('PRODUCT', 'PR'), ('SERVICE', 'SR'), ('CLASS', 'CL')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='main_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.DeleteModel(
            name='ProductCategoryLevel1',
        ),
        migrations.DeleteModel(
            name='ProductCategoryLevel2',
        ),
        migrations.DeleteModel(
            name='ProductCategoryLevel3',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
