# Generated by Django 5.0.1 on 2024-02-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_remove_product_level1_remove_product_level2_and_more'),
        ('projects', '0003_project_main_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('PR', 'PRODUCT'), ('SR', 'SERVICE'), ('CL', 'CLASS')], max_length=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='products', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('PR', 'PRODUCT'), ('SR', 'SERVICE'), ('CL', 'CLASS')], max_length=7, null=True),
        ),
    ]
