# Generated by Django 5.0.1 on 2024-02-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_alter_category_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('field', models.TextField()),
                ('products', models.ManyToManyField(null=True, to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
