# Generated by Django 5.0.1 on 2024-02-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='products',
            field=models.ManyToManyField(related_name='specifications', to='products.product'),
        ),
    ]
