# Generated by Django 5.0.1 on 2024-02-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_specification_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('PT', 'PART'), ('SR', 'SERVICE'), ('CL', 'CLASS')], max_length=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('PT', 'PART'), ('SR', 'SERVICE'), ('CL', 'CLASS')], max_length=7, null=True),
        ),
    ]
