# Generated by Django 5.0.1 on 2024-02-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_type_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vehicle',
            field=models.CharField(choices=[('HV', 'HEAVY'), ('LT', 'LIGHT')], default='LT', max_length=10),
        ),
    ]
